- name: Install required system packages
  apt: 
    name: {{ item }}
    update_cache: no
    state: latest 
  loop: [ 'apt-transport-https', 'ca-certificates', 'software-properties-common']

- name: Add Microsoft GPG apt key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VSCode Repository
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/vscode stable main
    state: present

- name: Update apt and install VSCode 
  apt: 
    update_cache: yes 
    name: code 
    state: latest
