- name: Install required system packages
  apt: 
    name: "{{ item }}"
    update_cache: no
    state: latest 
  loop: [ 'apt-transport-https', 'ca-certificates', 'software-properties-common']
  become: yes

- name: Add Microsoft GPG apt key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: yes
  
- name: Download MS product repository
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb

- name: Add VSCode Repository
  apt_repository:
    repo: deb packages-microsoft-prod.deb
    state: present
  become: yes

- name: Install VSCode 
  apt: 
    update_cache: yes 
    name: code 
    state: latest
  become: yes
